[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not,
# prints a warning asking for you to install it. The watchdog module is not required,
# it's just an optimization. If you know you don't want to install watchdog, you can
# suppress this warning by setting this to True.
disableWatchdogWarning = false

# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
showWarningOnDirectExecution = true

# DataFrame serialization.
dataFrameSerialization = "legacy"

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

# String format for logging messages. If logger.datetimeFormat is also set,
# logger.messageFormat will default to "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s".
# See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects)
# for available attributes.
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not connect to the Streamlit servers.
gatherUsageStats = true

# Max width in pixels for the main content area.
maxUploadSize = 200

# Max size in MB for uploaded files.
maxMessageSize = 200

[browser]

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Port where users can connect to the server.
serverPort = 8501

[server]

# List of folders that should not be watched for changes. This
# impacts both "Run on Save" and @st.cache.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off
# completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple
# replicas, this should be set to the same value across all replicas to ensure
# they all share the same secret.
cookieSecret = "nsna-mail-merge-secret-key-change-in-production"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address to which the server will bind itself.
address = "localhost"

# The port on which the server will listen for client connections.
port = 8501

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = true

# Max size in MB for the app's total memory usage.
maxUploadSize = 200

# Max size in MB for data frames.
maxMessageSize = 200

[theme]

# Primary accent color for interactive elements.
primaryColor = "#336699"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"
